USE [master]
GO

/****** Object:  Database [eComerce]    Script Date: 8/29/2022 3:09:12 PM ******/
CREATE DATABASE [eComerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eComerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\eComerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'eComerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\eComerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eComerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eComerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eComerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eComerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eComerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eComerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [eComerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eComerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eComerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eComerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eComerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eComerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eComerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eComerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eComerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eComerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eComerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eComerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eComerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eComerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eComerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eComerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eComerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eComerce] SET RECOVERY FULL 
GO

ALTER DATABASE [eComerce] SET  MULTI_USER 
GO

ALTER DATABASE [eComerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eComerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eComerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eComerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [eComerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [eComerce] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [eComerce] SET QUERY_STORE = OFF
GO

ALTER DATABASE [eComerce] SET  READ_WRITE 
GO

